### ISSUE TITLE
Java skeleton

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/code-review-action#1]

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#4](https://github.com/tracehubpm/code-review-action/issues/4), [#5](https://github.com/tracehubpm/code-review-action/issues/5), [#6](https://github.com/tracehubpm/code-review-action/issues/6) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#5](https://github.com/tracehubpm/code-review-action/issues/5), [#6](https://github.com/tracehubpm/code-review-action/issues/6) are still not solved; solved: [#4](https://github.com/tracehubpm/code-review-action/issues/4).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#5](https://github.com/tracehubpm/code-review-action/issues/5) is still not solved; solved: [#4](https://github.com/tracehubpm/code-review-action/issues/4), [#6](https://github.com/tracehubpm/code-review-action/issues/6).
