### ISSUE TITLE
SkipIfMentioned.java:25-29: apply SkipIfMentioned too...

### ISSUE THREAD

**Issue by 0pdd** [tracehubpm/code-review-action#101]
The puzzle `85-d5fc9715` from #85 has to be resolved: 

https://github.com/tracehubpm/code-review-action/blob/ce2df04b0302c910f05f76e68298764ef0d09d43/src/main/java/git/tracehub/codereview/action/SkipIfMentioned.java#L25-L29

The puzzle was created by @h1alexbel on 09-May-24. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
@l3r8yJ do you want to take it?

**Comment by l3r8yJ** [comment]
@h1alexbel sure

**Comment by h1alexbel** [comment]
@l3r8yJ okay, assigned

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#109](https://github.com/tracehubpm/code-review-action/issues/109), [#110](https://github.com/tracehubpm/code-review-action/issues/110) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#109](https://github.com/tracehubpm/code-review-action/issues/109) is still not solved; solved: [#110](https://github.com/tracehubpm/code-review-action/issues/110).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#109](https://github.com/tracehubpm/code-review-action/issues/109), [#110](https://github.com/tracehubpm/code-review-action/issues/110).
