### ISSUE TITLE
Deep infra integration

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/code-review-action#60]
we should integrate [deepinfra models](https://deepinfra.com), like we did in https://github.com/tracehubpm/reports-check-action

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#63](https://github.com/tracehubpm/code-review-action/issues/63) is still not solved.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.19`

**Comment by 0pdd** [comment]
@h1alexbel the only puzzle [#63](https://github.com/tracehubpm/code-review-action/issues/63) is solved here.
