### ISSUE TITLE
Ignore pull requests by `renovate-bot` and `dependabot`

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/code-review-action#85]
Let's ignore pull requets from the analysis if it was submitted by either renovate-bot or dependabot

**Comment by l3r8yJ** [comment]
@h1alexbel assign this one to me, pls

**Comment by h1alexbel** [comment]
@l3r8yJ go ahead!

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#101](https://github.com/tracehubpm/code-review-action/issues/101) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#109](https://github.com/tracehubpm/code-review-action/issues/109), [#110](https://github.com/tracehubpm/code-review-action/issues/110) are still not solved; solved: [#101](https://github.com/tracehubpm/code-review-action/issues/101).

**Comment by 0pdd** [comment]
@h1alexbel all 3 puzzles are solved here: [#101](https://github.com/tracehubpm/code-review-action/issues/101), [#109](https://github.com/tracehubpm/code-review-action/issues/109), [#110](https://github.com/tracehubpm/code-review-action/issues/110).
