### ISSUE TITLE
ChatGPT integration

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/code-review-action#88]
Let's integrate ChatGPT too

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#126](https://github.com/tracehubpm/code-review-action/issues/126), [#127](https://github.com/tracehubpm/code-review-action/issues/127) are still not solved.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.3.0`
