### ISSUE TITLE
migrate to Java 21

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/code-review-action#96]
Let's migrate to Java 21, to do so we should change `java.version` to `21` and try to merge [this pull request](https://github.com/tracehubpm/code-review-action/pull/84)

**Comment by YasenevGleb** [comment]
Hello @h1alexbel , can I take this issue?

**Comment by h1alexbel** [comment]
@YasenevGleb hi! sure, go ahead!

**Comment by YasenevGleb** [comment]
@h1alexbel created a pull request, please take a look
https://github.com/tracehubpm/code-review-action/pull/121
